### ISSUE TITLE
Add PGA to the GUI?

### ISSUE THREAD

**Issue by timmaybrown** [dfs-with-r/shinycoach#1]
Looks like the coach repo supports PGA, but the upload PGA lineup and optimizer isn't available in this GUI.

Any chance to support this? 

I can try to submit a PR as I'm interested into diving into the basics of R.

**Comment by zamorarr** [comment]
hey @timmaybrown . Yup I can look into this. Any particular fantasy site you are using? And if you have  PR I'd be more than happy to look it over!

**Comment by zamorarr** [comment]
The fix was easier than I thought since as you said I already had them in coach. The options should be working now in the GUI. Feel free to try at https://zamora.shinyapps.io/shinycoach/ or re-install this repo and try locally.

Thanks for the suggestion!
